# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.backgroundErrors", 2);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1622554494);
user_pref("app.update.lastUpdateTime.background-update-timer", 1622617967);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1622617449);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1622617569);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1622617689);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20130511120803");
user_pref("browser.startup.homepage_override.mstone", "21.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1622634279403");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1622617908885");
user_pref("datareporting.policy.firstRunTime", "1622547879403");
user_pref("datareporting.sessions.current.activeTicks", 14);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1148);
user_pref("datareporting.sessions.current.main", 357);
user_pref("datareporting.sessions.current.sessionRestored", 1197);
user_pref("datareporting.sessions.current.startTime", "1622617846392");
user_pref("datareporting.sessions.current.totalTime", 141);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1622547877982,\"a\":41,\"t\":276,\"c\":true,\"m\":371,\"fp\":5959,\"sr\":7049}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1622554285727,\"a\":9,\"t\":80,\"c\":true,\"m\":515,\"fp\":1595,\"sr\":1658}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1622554372602,\"a\":24,\"t\":146,\"c\":true,\"m\":575,\"fp\":1583,\"sr\":1641}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1622617328549,\"a\":37,\"t\":412,\"c\":true,\"m\":163,\"fp\":938,\"sr\":993}");
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:21.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/auto/HPC/cae-ws-apps01/apps/all/applications/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1368305546000,\"rdfTime\":1368305135000}}}]");
user_pref("extensions.lastAppVersion", "21.0");
user_pref("extensions.lastPlatformVersion", "21.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130511120803");
user_pref("gecko.mstone", "21.0");
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.autoconfig_url", "http://pac.seat.vwgroup.com/seat.es/seatz.pac");
user_pref("network.proxy.type", 2);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.soname.list", "libXt.so:libXext.so");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.disable_button.openDeviceManager", false);
user_pref("toolkit.startup.last_success", 1622617846);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1625209619);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
